pipeline {
  agent {
    docker {
      image 'node:20'  // 使用 Node.js 官方镜像
    }
  }
  environment {
    ALLURE_RESULTS = 'allure-results'
    ALLURE_REPORT = 'allure-report'
  }

  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/Toocomplicated/selenium-allure-demo.git'
      }
    }

    stage('Install dependencies') {
      steps {
        sh 'npm install'
      }
    }

    stage('Run Tests') {
      steps {
        sh 'rm -rf allure-results || true'
        sh 'ALLURE_OUTPUT_DIR=allure-results npx mocha test/*.spec.js --reporter allure-mocha'
      }
    }

    stage('Generate Allure Report') {
      steps {
        sh 'npx allure generate allure-results --clean -o allure-report'
      }
    }

    stage('Publish Allure Report') {
      steps {
        allure includeProperties: false, jdk: '', reportBuildPolicy: 'ALWAYS', results: [[path: 'allure-results']]
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: 'allure-report/**/*', fingerprint: true
    }
  }
}
