pipeline {
  agent {
    docker {
      image 'selenium/standalone-chrome:latest' // 带 Chrome + Node 环境
      args '-u root:root' // 保证容器里有权限
    }
  }

  environment {
    ALLURE_RESULTS = 'allure-results'
    ALLURE_REPORT = 'allure-report'
  }

  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/Toocomplicated/selenium-allure-demo.git'
      }
    }

    stage('Install dependencies') {
      steps {
        sh 'npm install'
      }
    }

    stage('Run Tests') {
      steps {
        catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
          sh '''
            rm -rf $ALLURE_RESULTS || true
            ALLURE_OUTPUT_DIR=$ALLURE_RESULTS npx mocha test/*.spec.js --reporter allure-mocha
          '''
        }
      }
    }

    stage('Generate Allure Report') {
      steps {
        sh 'npx allure generate $ALLURE_RESULTS --clean -o $ALLURE_REPORT || true'
      }
    }

    stage('Publish Allure Report') {
      steps {
        allure includeProperties: false, jdk: '', reportBuildPolicy: 'ALWAYS', results: [[path: '$ALLURE_RESULTS']]
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: '$ALLURE_REPORT/**/*', fingerprint: true
    }
  }
}
