name: Run tests and deploy Allure report

on:
  push:
    branches:
      - main  # 修改为你的默认分支名（如 master）.

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      # - name: Run tests and generate allure-results
      #   run: |
      #     rm -rf allure-results || true
      #     ALLURE_OUTPUT_DIR=allure-results npx mocha test/*.spec.js --reporter allure-mocha
      #   continue-on-error: true
      - name: Clean old results
        run: rm -rf allure-results || true

      - name: Run tests
        run: |
          ALLURE_OUTPUT_DIR=allure-results npx mocha test/*.spec.js --reporter allure-mocha || true


      - name: Generate Allure report
        if: always()  
        run: |
          npx allure generate allure-results --clean -o allure-report
      - name: Generate Allure report
        run: |
          npx allure generate allure-results --clean -o allure-report
      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
